[package]
name = "key2words"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later" # (apache or mit) and gplv2+ and BSD-3clause
authors = ["Justin Martin"]

[dependencies]
bip39 = "2.0"
ssh-key = { version = "0.5", features = ["alloc", "std", "ed25519", "encryption", "getrandom"] }
zeroize = "1.6"
clap = {version = "4.3", features = ["derive"]}
sha3 = "0.10"
sha2 = "0.10"
base32ct = {version = "0.2.0", features = ["alloc"] }

sequoia-openpgp = { version = "1.16", default-features = false, features = ["crypto-rust",  "allow-experimental-crypto", "allow-variable-time-crypto"] }
x25519-dalek = { version = "2.0.0-rc.2", features = ["static_secrets"] }
anyhow = "1.0.71"

[dev-dependencies]
base64ct = {version = "1.6.0", features = ["alloc"]}
