[package]
name = "key2words"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "1.0"
ssh-key = { version = "0.4", features = ["alloc", "std", "ed25519", "encryption", "getrandom"] }
zeroize = "1.5"
clap = {version = "3.2", features = ["derive"]}
