[package]
name = "key2words"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
authors = ["Justin Martin"]

[dependencies]
tiny-bip39 = "1.0"
ssh-key = { version = "0.4", features = ["alloc", "std", "ed25519", "encryption", "getrandom"] }
zeroize = "1.5"
clap = {version = "3.2", features = ["derive"]}
sha3 = "0.10.2"
sha2 = "0.10.3"
base32ct = {version = "0.1.0", features = ["alloc"] }

[dev-dependencies]
base64ct = {version = "1.5.2", features = ["alloc"]}
