[workspace]
members = [
    "web",
    "cli",
    "core"
]

default-members = ["cli"]

resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
bip39 = { version = "2.0", features = ["rand"]}


[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

[profile.bench]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3
