[package]
name = "key2words"
version = "0.1.0"
edition = "2021"

[dependencies]
bip39 = "1.0"
ssh-key = { git = "https://github.com/RustCrypto/formats", features = ["alloc", "std", "ed25519"] }
ed25519-dalek = "1.0"
zeroize = "1.5"
clap = {version = "3.1", features = ["derive"]}
