[package]
name = "key2words-web"
version = "0.1.0"
edition = "2021"
license = "LGPL-2.0-or-later" # (apache or mit) and lgplv2+ and BSD-3clause
authors = ["Justin Martin"]

[dependencies]
key2words-core = { version = "0.1.0", path = "../core" }
anyhow = { workspace = true }
bip39 = { workspace = true }

ybc = "0.4.0"
gloo = "0.8.0"
yew = { version = "0.20.0", features = ["csr"]}
stylist = { version = "0.12.1", features = ["yew_integration"]}
yew-agent = "0.2.0"
serde = { version = "<=1.0.171", features = ["derive"] } # pin to avoid prebuilt binaries
getrandom = { version = "0.2.10", features = ["js"]} # stdweb web crypto for rng
web-sys = { version = "^0.3.64", features = ["HtmlElement", "Document", "Element"]}
wasm-bindgen = "0.2"
base64ct = { version = "1.6.0", features = ["alloc"]}
